#!/bin/bash
user=root
password=1
dbs="r2_characters r2_characters_19 r2_characters_29 r2_characters_20 r2_characters_60 r2_characters_70 r2_world r2_realm r2_scripts mangoszero_characters mangoszero_world mangoszero_realm mangoszero_scripts mangosone_characters mangosone_world mangosone_realm mangosone_scripts mangostwo_characters mangostwo_world mangostwo_realm mangostwo_scripts cmangos_characters cmangos_world cmangos_realm cmangos_scripts armory"
